CREATE TABLE MOVIE(
    MOVIE_ID BIGSERIAL PRIMARY KEY,
    MOVIE_NAME TEXT NOT NULL,
    MOVIE_TAGS TEXT NOT NULL,
    MOVIE_POSTER_URL TEXT NOT NULL
);

CREATE TABLE USERS(
    USER_ID BIGSERIAL PRIMARY KEY,
    USERNAME TEXT NOT NULL UNIQUE,
    EMAIL TEXT NOT NULL,
    PASSWORD TEXT NOT NULL
);

CREATE TABLE SCREEN(
    SCREEN_ID BIGSERIAL PRIMARY KEY,
    THEATRE_ID BIGINT NOT NULL UNIQUE,
    SEATS_NUM INTEGER NOT NULL
);

CREATE TABLE SCREENING(
    SCREENING_ID BIGSERIAL PRIMARY KEY,
    THEATRE_ID BIGINT NOT NULL UNIQUE,
    SCREEN_ID BIGINT NOT NULL UNIQUE,
    MOVIE_NAME TEXT NOT NULL,
    SCREENING_DATE DATE NOT NULL,
    SCREENING_TIME TIME NOT NULL,
    BOOKED_TICKETS INTEGER NOT NULL
);

CREATE TABLE THEATRE(
    THEATRE_ID BIGSERIAL PRIMARY KEY,
    THEATRE_NAME TEXT NOT NULL,
    THEATRE_CITY TEXT NOT NULL
);

CREATE TABLE TICKET(
    TICKET_ID BIGSERIAL PRIMARY KEY,
    SCREENING_ID BIGINT NOT NULL,
    SEAT_NUM INTEGER NULL
);