CREATE FUNCTION role_cast(varchar) RETURNS ROLE AS $$
    SELECT CASE $1
        WHEN 'CUSTOMER' THEN 'CUSTOMER'::ROLE
        WHEN 'EMPLOYEE' THEN 'EMPLOYEE'::ROLE
    END;
$$ LANGUAGE SQL;

CREATE CAST (varchar AS ROLE) WITH FUNCTION role_cast(varchar) AS ASSIGNMENT;